---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

The LCMS-Based Untargeted Metabolomics Assistant package (LUMA) performs quality control (QC) and feature reduction steps on the output of XCMS and CAMERA to generate usable data matrices for discovery-based studies.
    The outputs of XCMS and CAMERA consist of peak matrices for each feature detected by XCMS and annotated by CAMERA.  These can contain spurious features and annotations or real features that do not pass basic QC checks, which can hinder downstream statistical analyses.  Therefore, curation of these matrices must be performed to ensure quality of the resulting dataset. Often these steps are performed manually and can be very time-consuming.
    LUMA provides rapid, automated workflows to perform the necessary QC and feature reduction steps with minimal user input. Visual inspection of the data is consolidated to two steps to minimize the user's time spent validating the dataset, particularly when summing features into a single value per metabolite (an important QC check!). Study parameters are provided to the workflow via external text- or comma-separated files, and LUMA does the rest!
