#' @title Parses CAMERA annotations
#'
#' @description Parses the three annotation columns generated by CAMERA to remove redundant and duplicative ion adduct annotations
#' See parse_pos_results, parse_neg_results and plot_metgroup for more details.
#' #' @param from.table from which table should LUMA pull the Peak.list
#' @param to.table to which should LUMA save the modified Peak.list
ParseCAMERA <- function(from.table,to.table) {
  ## Section of code to parse the output from CAMERA and plot results ######
  .set_LUMAmsg("Validating CAMERA annotations!")

  Peak.list <- read_tbl(mytable = from.table,
                        peak.db = peak_db,
                        asdf = TRUE)

  ## Run the CAMERA Parser
  if(ion.mode == "Positive"){
    new.Peak.list <- parse_pos_results(raw = Peak.list,
                                   rule = rules,
                                   ion.mode = ion.mode)
  } else {
    if(ion.mode == "Negative"){
      new.Peak.list <- parse_neg_results(raw = Peak.list,
                                     rule = rules,
                                     ion.mode = ion.mode)
    }
  }

  write_tbl(mydf = new.Peak.list,
            peak.db = peak_db,
            myname = "input_parsed")

  ## Call to function which plots EICs, pspectra, dendrograms and correlation matrices for metabolite groups that contain more than one feature.
  ## Necessary to determine if adducts are real.
  #READ in the CAMERA Parsed peak list with Metabolite IDs
  Peak.list <- read_tbl(mytable = "input_parsed",
                        peak.db = peak_db,
                        asdf = TRUE)

  myresults <- plot_metgroup(anposGa = anposGa,
                             Sample.df = Sample.df,
                             Peak.list = Peak.list,
                             center = XCMS.par$center,
                             BLANK = BLANK,
                             gen.plots = search.par$gen.plots,
                             ion.mode = ion.mode,
                             file.base = file.base)

  write_tbl(mydf = myresults[[1]],
            peak.db = peak_db,
            myname = to.table)

  write_xlsx(validate.sheets = myresults[[2]],
             file.base = DataFiles,
             myname = "Validate Metabolite Groups",
             mysheets = c("clear","muddy"))

  ## End parsing and plotting section ####

}

#' @title Combines Features into Metabolites
#'
#' @description Combines all well-behaved features in metabolite groups into a single entry per metabolite.
#' See sum_features and combine_phenodata for more details.
#' @param from.table from which table should LUMA pull the Peak.list
#' @param to.table to which should LUMA save the modified Peak.list
CombineFeatures <- function(from.table,to.table) {
  ## Sums isotopic and adduct peaks and combined all feature data into a single metadata entry

  Peak.list <- read_tbl(mytable = from.table,
                        peak.db = peak_db,
                        asdf = TRUE)

  Summed.list <- sum_features(Sample.df = data.frame(Sex = Sex,
                                                        Class = Class,
                                                        n = no.Samples,
                                                        Endogenous = Endogenous),
                                 Peak.list = Peak.list,
                                 search.par = data.frame(ppm = ppm.cutoff,
                                                         rt = rt.cutoff,
                                                         Voidrt = Voidrt,
                                                         Corr.stat.pos = Corr.stat.pos,
                                                         Corr.stat.neg = Corr.stat.neg,
                                                         CV = cv.cutoff,
                                                         Minfrac = mf.cutoff,
                                                         Endogenous = Endogenous.thresh,
                                                         Solvent = Solvent.ratio,
                                                         gen.plots = gen.plots,
                                                         keep.singletons = keep.singletons),
                                 BLANK = BLANK,
                                 ion.mode = ion.mode)

  #Combine phenotype data for each metabolite group with summed intensity values
  new.Peak.list <- combine_phenodata(Sample.df = data.frame(Sex = Sex,
                                                               Class = Class,
                                                               n = no.Samples,
                                                               Endogenous = Endogenous),
                                        Peak.list = Peak.list,
                                        Summed.list = Summed.list,
                                        search.par = data.frame(ppm = ppm.cutoff,
                                                                rt = rt.cutoff,
                                                                Voidrt = Voidrt,
                                                                Corr.stat.pos = Corr.stat.pos,
                                                                Corr.stat.neg = Corr.stat.neg,
                                                                CV = cv.cutoff,
                                                                Minfrac = mf.cutoff,
                                                                Endogenous = Endogenous.thresh,
                                                                Solvent = Solvent.ratio,
                                                                gen.plots = gen.plots,
                                                                keep.singletons = keep.singletons),
                                        BLANK = BLANK,
                                        ion.mode = ion.mode)
  write_tbl(mydf = new.Peak.list,
            peak.db = peak_db,
            myname = to.table)

}
